import React from "react";
import Footer from "../components/Footer"; // Ensure the footer component exists
import "../styles/TermsConditions.css";

const PrivacyPolicy = () => {
  return (
    <div className="privacy-container">
      <header className="privacy-header">
        <h1>TERMS & CONDITIONS</h1>
            Effective Date: [21/03/2025] <br />version 1.0

        <p>
        This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
<br /> <br />
The website www.loomiz.in (“website”) and mobile application ‘Loomiz’(App) (website and App collectively referred to as the “platform”) is owned, operated and managed by the Gama Textiles Private Limited, a company incorporated in accordance with the provisions of the Indian Companies Act, 2013 and having its registered office at 3rd floor, The Statement, Gurgaon, Haryana, 122022.
<br /> <br />
This Terms of Use (“Terms”) governs your access and use of the Loomiz website and mobile application (“Platform”), owned and operated by Gama Textiles Private Limited (“Company”, “Loomiz”, “we”, “us”, or “our”). By accessing or using the Platform and our services (“Services”), you agree to be bound by these Terms and Conditions
<br /><br />
Please read these Terms carefully. If you do not agree with any part of these Terms, you should not access or use the Platform.
          
        </p>
      </header>

      <div className="privacy-content">
        {/* Sidebar Section */}
        <aside className="privacy-sidebar">
          <ul>
            <li>1. WHO CAN USE LOOMIZ</li>
            <li>2. OUR SERVICES</li>
            <li>3. ACCOUNT REGISTRATION</li>
            <li>4. VENDOR ONBOARDING</li>
            <li>5. USE OF THE PLATFORM</li>
            <li>6. PAYMENTS & PRICING</li>
            <li>7. QUALITY ASSURANCE</li>
            <li>8. INTELLECTUAL PROPERTY</li>
            <li>9. PRIVACY</li>
            <li>10. LIMITATION OF LIABILITY</li>
            <li>11. TERMINATION</li>
            <li>12. UPDATES TO TERMS</li>
            <li>13. GOVERNING LAW</li>
            <li>14. CONTACT US</li>
          </ul>
        </aside>

        {/* Main Content Section */}
        <main className="privacy-main">
          <section>
            <h2>1. WHO CAN USE LOOMIZ</h2>
            <ul>
            You must be at least 18 years of age and legally capable of entering into contracts to use our Platform. If you're using the Platform on behalf of a company or entity, you confirm that you're authorized to bind it to these Terms.
            </ul>
          </section>

          

          <section>
            <h2>2. OUR SERVICES</h2>
            <ul>
            Loomiz provides global fashion brands with access to streamlined, tech-enabled apparel manufacturing services. Our services include:
              <ul>
                <li>
                AI-powered design tools
                </li>
                <li>
                3D prototyping and virtual sampling
                </li>
                <li>
                Manufacturing management
                </li>
                <li>
                Quality control with real-time reports
                </li>
                <li>
                Global logistics and delivery management
                </li>
              </ul>
              We do not manufacture products ourselves but work with a network of vetted, compliant manufacturers.
            </ul>
          </section>

          <section>
            <h2>3. ACCOUNT REGISTRATION</h2>
            <ul>
            To use certain features, you must register and create an account. You are responsible for keeping your login credentials secure. Any activity under your account is your responsibility.
            </ul>
          </section>

          <section>
            <h2>4. VENDOR ONBOARDING</h2>
            <ul>
            Suppliers and manufacturers who wish to be listed on Loomiz must fill out the onboarding form. We evaluate vendors based on machinery, capacity, existing clientele, and compliance before formal onboarding through a signed contract.
            </ul>
          </section>

          <section>
            <h2>5. USE OF THE PLATFORM</h2>
            <ul>
            You agree not to: 
              <ul>

                <li>Use the platform for any unlawful purpose.</li>
<li>Attempt to reverse-engineer or hack the platform.</li>
<li>Upload content that infringes intellectual property or is harmful, abusive, or deceptive.</li>
<li>Violate any local, national, or international laws in your use of our services.</li>
              </ul>
              <br />
              To exercise these rights, contact us at privacy@loomiz.com.
            </ul>
          </section>

          <section>
            <h2>6. PAYMENTS & PRICING</h2>
            <ul>
            Pricing for services and products will be clearly communicated before confirmation. Loomiz may use third-party payment providers, and by using them, you agree to their terms.
            </ul>
          </section>

          <section>
            <h2>7. QUALITY ASSURANCE</h2>
            <ul>
            We provide detailed QC reports, including images and videos, before shipment. You may request revisions, and our team will coordinate with manufacturers to execute changes if required.
            </ul>
          </section>
<section>
            <h2>8. INTELLECTUAL PROPERTY</h2>
            <ul>
            All content on Loomiz (text, logos, graphics, tools) is the intellectual property of Loomiz or its licensors. You may not copy, distribute, or reuse without permission.
            </ul>
          </section>
          <section>
            <h2>9. PRIVACY</h2>
            <ul>
            Your data is handled as per our Privacy Policy. We do not sell your personal information. For full details, please review our Privacy Policy on the Platform.
            </ul>
          </section>

          

          <section>
            <h2>10. LIMITATION OF LIABILITY</h2>
            <ul>
            Loomiz will not be liable for any indirect, incidental, special, or consequential damages arising from the use of our Platform or services.
            </ul>
          </section>

          <section>
            <h2>11. TERMINATION</h2>
            <ul>
            We may suspend or terminate your access to the Platform if you breach these Terms or misuse our services. You may also deactivate your account at any time by contacting us.</ul>
          </section>

          <section>
            <h2>12. UPDATES TO TERMS</h2>
            <ul>
            We reserve the right to update these Terms at any time. Any changes will be posted on this page. Your continued use of the Platform constitutes acceptance of the updated Terms.</ul>
          </section>

          <section>
            <h2>13. GOVERNING LAW</h2>
            <ul>
            These Terms are governed by Indian laws. Any disputes shall be subject to the jurisdiction of the courts in [Insert City], India. </ul>
          </section>

          <section className="contactus">
            <h2>14. CONTACT US</h2>
            <ul>
            If you have any questions about these Terms, you can contact: <br />
              <strong>Grievance Officer:</strong> <br />
              Name: Rajesh Mejari <br />
              Email: Compliancel@loomiz.in
            </ul>
          </section>
        </main>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
